version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tcp:den1.mssql7.gear.host,1433;Database=wypozyczalniaa;User Id=wypozyczalniaa;Password=Fn77Z_-Qq871;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"

